services:
    api:
        build:
            context: ./docker/sail/php
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-electric/app'
        container_name: sail-electric-php
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            pgsql:
                condition: service_healthy
    pgadmin:
        container_name: sail-electric-pgadmin
        image: dpage/pgadmin4
        ports:
            - '5050:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL:-admin@admin.com}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD:-admin}'
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        networks:
            - sail
        depends_on:
            pgsql:
                condition: service_healthy
    electric:
        image: docker.io/electricsql/electric:1.1.6
        container_name: sail-electric
        environment:
            DATABASE_URL: 'postgresql://${DB_USERNAME}:${DB_PASSWORD:-secret}@pgsql:5432/${DB_DATABASE}?sslmode=disable'
            # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
            # See https://electric-sql.com/docs/guides/security
            ELECTRIC_INSECURE: true
        # ports:
        #     - "3000:3000"
        networks:
            - sail
        depends_on:
            pgsql:
                condition: service_healthy
    pgsql:
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/sail/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        command:
            - -c
            - wal_level=logical
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    pgadmin_data:
        driver: local
